services:
  t5g1:
    image: t5g1:latest   
    build:
      context: .
    entrypoint: ["false"]

  frontend:
    image: t5g1:latest    
    command: python webpage.py
    ports: ["8050:8050"]
    environment:
      - FLASK_API_URL=http://127.0.0.1:5000
    depends_on: [t5g1,backend]
    networks: [sharednet]


  backend:
    image: t5g1:latest
    command: flask --app flask_backend run 
    ports: ["5000:5000"]
    depends_on: [t5g1]
    networks: [sharednet]

networks:
  sharednet:
    driver: bridge