version: "3.8"

services:
  frontend:
    build: .
    command: python webpage.py 
    ports:
      - "8050:8050"
    depends_on:
      - backend
    environment:
      - FLASK_API_URL=http://127.0.0.1:5000
    networks:
      - sharednet

  backend:
    build: .
    command: python flask_backend.py
    ports:
      - "5000:5000"
    networks:
      - sharednet

networks:
  sharednet:
    driver: bridge