version: "3.8"

services:
  dash:
    build: ./dash_app
    ports:
      - "8050:8050"
    depends_on:
      - flask
    environment:
      - FLASK_API_URL=http://flask:5000
    networks:
      - dashnet

  flask:
    build: ./flask_backend
    ports:
      - "5000:5000"
    networks:
      - dashnet

networks:
  dashnet:
    driver: bridge